// <auto-generated />
using System;
using KazanRealEstate.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KazanRealEstate.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507144148_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KazanRealEstate.Api.Repositories.Tables.Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Developers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Лидер рынка Татарстана, известный своими проектами 'Царево Village' и 'Весна'.",
                            Name = "Унистрой",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 2,
                            Description = "Один из старейших застройщиков региона с широким портфелем проектов.",
                            Name = "Ак Барс Дом",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 3,
                            Description = "Застройщик, специализирующийся на современной архитектуре и качественной среде.",
                            Name = "СМУ-88",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 4,
                            Description = "Бутик-застройщик, работающий с историческим центром и элитной недвижимостью.",
                            Name = "КамаСтройИнвест",
                            Rating = 4.9000000000000004
                        });
                });

            modelBuilder.Entity("KazanRealEstate.Api.Repositories.Tables.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ResidentialComplexId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResidentialComplexId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("KazanRealEstate.Api.Repositories.Tables.ResidentialComplex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BuildingMaterial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DeveloperId")
                        .HasColumnType("integer");

                    b.Property<double>("DistanceToCenter")
                        .HasColumnType("double precision");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("EcologicalRating")
                        .HasColumnType("double precision");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("InfrastructureRating")
                        .HasColumnType("double precision");

                    b.Property<decimal>("MaxPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.ToTable("ResidentialComplexes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "",
                            BuildingMaterial = "Brick",
                            Class = "Эко-поселок",
                            CompletionDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Уютный пригородный поселок с парками, школами и уникальной атмосферой.",
                            DeveloperId = 1,
                            DistanceToCenter = 15.5,
                            District = "Пестречинский",
                            EcologicalRating = 4.7999999999999998,
                            ImageUrl = "https://images.unsplash.com/photo-1570129477492-45c003edd2be?q=80&w=800",
                            InfrastructureRating = 3.5,
                            MaxPrice = 8500000m,
                            MinPrice = 4500000m,
                            Name = "ЖК Царево Village"
                        },
                        new
                        {
                            Id = 2,
                            Address = "",
                            BuildingMaterial = "Brick-Monolith",
                            Class = "Комфорт+",
                            CompletionDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Большой семейный комплекс с развитой инфраструктурой и закрытыми дворами.",
                            DeveloperId = 1,
                            DistanceToCenter = 9.1999999999999993,
                            District = "Советский",
                            EcologicalRating = 4.0,
                            ImageUrl = "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=800",
                            InfrastructureRating = 4.2000000000000002,
                            MaxPrice = 13000000m,
                            MinPrice = 6500000m,
                            Name = "ЖК Весна"
                        },
                        new
                        {
                            Id = 3,
                            Address = "",
                            BuildingMaterial = "Monolith",
                            Class = "Бизнес-лайт",
                            CompletionDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Современный жилой массив рядом с ТЦ Мега и будущей станцией метро.",
                            DeveloperId = 2,
                            DistanceToCenter = 7.5,
                            District = "Советский",
                            EcologicalRating = 3.5,
                            ImageUrl = "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=800",
                            InfrastructureRating = 4.5,
                            MaxPrice = 16000000m,
                            MinPrice = 7500000m,
                            Name = "ЖК Мой Ритм"
                        },
                        new
                        {
                            Id = 4,
                            Address = "",
                            BuildingMaterial = "Monolith",
                            Class = "Бизнес",
                            CompletionDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Премиальный комплекс с видом на Казанку и Кремль в самом центре Кварталов.",
                            DeveloperId = 3,
                            DistanceToCenter = 3.2000000000000002,
                            District = "Ново-Савиновский",
                            EcologicalRating = 3.7999999999999998,
                            ImageUrl = "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=800",
                            InfrastructureRating = 4.7999999999999998,
                            MaxPrice = 45000000m,
                            MinPrice = 15000000m,
                            Name = "ЖК Savin House"
                        },
                        new
                        {
                            Id = 5,
                            Address = "",
                            BuildingMaterial = "Monolith",
                            Class = "Элит",
                            CompletionDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Стеклянные башни на берегу реки с панорамным остеклением и яхт-клубом.",
                            DeveloperId = 3,
                            DistanceToCenter = 2.5,
                            District = "Кировский",
                            EcologicalRating = 3.5,
                            ImageUrl = "https://images.unsplash.com/photo-1475855581690-804d4628733c?q=80&w=800",
                            InfrastructureRating = 4.7000000000000002,
                            MaxPrice = 60000000m,
                            MinPrice = 18000000m,
                            Name = "ЖК Atlantis Deluxe"
                        },
                        new
                        {
                            Id = 6,
                            Address = "",
                            BuildingMaterial = "Brick",
                            Class = "Элит",
                            CompletionDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Клубный дом в историческом центре Казани рядом с парком 'Черное озеро'.",
                            DeveloperId = 4,
                            DistanceToCenter = 0.5,
                            District = "Вахитовский",
                            EcologicalRating = 4.2000000000000002,
                            ImageUrl = "https://images.unsplash.com/photo-1460317442991-0ec23938714b?q=80&w=800",
                            InfrastructureRating = 5.0,
                            MaxPrice = 80000000m,
                            MinPrice = 25000000m,
                            Name = "ЖК Vincent"
                        },
                        new
                        {
                            Id = 7,
                            Address = "",
                            BuildingMaterial = "Monolith",
                            Class = "Комфорт",
                            CompletionDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Яркий жилой комплекс рядом со станцией метро 'Аметьево'.",
                            DeveloperId = 2,
                            DistanceToCenter = 6.0,
                            District = "Приволжский",
                            EcologicalRating = 3.0,
                            ImageUrl = "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=800",
                            InfrastructureRating = 4.0,
                            MaxPrice = 12000000m,
                            MinPrice = 6000000m,
                            Name = "ЖК Легенда"
                        });
                });

            modelBuilder.Entity("KazanRealEstate.Api.Repositories.Tables.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KazanRealEstate.Api.Repositories.Tables.Favorite", b =>
                {
                    b.HasOne("KazanRealEstate.Api.Repositories.Tables.ResidentialComplex", "ResidentialComplex")
                        .WithMany()
                        .HasForeignKey("ResidentialComplexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KazanRealEstate.Api.Repositories.Tables.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResidentialComplex");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KazanRealEstate.Api.Repositories.Tables.ResidentialComplex", b =>
                {
                    b.HasOne("KazanRealEstate.Api.Repositories.Tables.Developer", "Developer")
                        .WithMany("Projects")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("KazanRealEstate.Api.Repositories.Tables.Developer", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
