// <auto-generated />
using System;
using KazanRealEstate.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KazanRealEstate.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506061349_AddUsersTable")]
    partial class AddUsersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KazanRealEstate.Api.Models.Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Developers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Один из крупнейших застройщиков Татарстана.",
                            Name = "Унистрой",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 2,
                            Description = "Государственный холдинг, строящий современные ЖК.",
                            Name = "Ак Барс Дом",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 3,
                            Description = "Застройщик премиального и комфорт-класса.",
                            Name = "СМУ-88",
                            Rating = 4.7000000000000002
                        });
                });

            modelBuilder.Entity("KazanRealEstate.Api.Models.ResidentialComplex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeveloperId")
                        .HasColumnType("integer");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MaxPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.ToTable("ResidentialComplexes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "",
                            Class = "Эко-поселок",
                            DeveloperId = 1,
                            District = "Пестречинский/Советский",
                            MaxPrice = 8000000m,
                            MinPrice = 4000000m,
                            Name = "ЖК Царево"
                        },
                        new
                        {
                            Id = 2,
                            Address = "",
                            Class = "Комфорт",
                            DeveloperId = 1,
                            District = "Советский",
                            MaxPrice = 12000000m,
                            MinPrice = 6000000m,
                            Name = "ЖК Весна"
                        },
                        new
                        {
                            Id = 3,
                            Address = "",
                            Class = "Бизнес-лайт",
                            DeveloperId = 2,
                            District = "Советский",
                            MaxPrice = 15000000m,
                            MinPrice = 7000000m,
                            Name = "ЖК Мой Ритм"
                        });
                });

            modelBuilder.Entity("KazanRealEstate.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KazanRealEstate.Api.Models.ResidentialComplex", b =>
                {
                    b.HasOne("KazanRealEstate.Api.Models.Developer", "Developer")
                        .WithMany("Projects")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("KazanRealEstate.Api.Models.Developer", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
